version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  github-pages: circleci/github-pages@0.1.4

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

  deploy-javadoc:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - github-pages/deploy:
          branch: gh-pages
          folder: target/apidocs

workflows:
  build-and-upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-javadoc:
          requires:
            - build
          filters:
            branches:
              only:
                - master
