version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

  deploy-javadoc:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Create gh-pages branch if it doesn't exist
          command: |
            git fetch origin
            git branch -a | grep remotes/origin/gh-pages || git checkout --orphan gh-pages
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.name "circleci"
            git config --global user.email "circleci@users.noreply.github.com"
            git clone --branch gh-pages https://oauth2:${akram}@github.com/akrambourouina/ceri-m1-techniques-de-test.git target/gh-pages
            cp -R target/site/apidocs/* target/gh-pages/
            cd target/gh-pages
            git add .
            git commit -m "Deploy Javadoc"
            git push origin gh-pages


workflows:
  build-and-upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-javadoc:
          requires:
            - build
          filters:
            branches:
              only:
                - master
